from odoo import api, fields, models, _
from odoo.exceptions import UserError


_INSTRUCTIONS_SERVER_HTML = """
<ol>
    <li>Plug the IoT Box into power and ethernet.</li>
    <li>Open the box's homepage (printed on the sticker or found via
        <b>iot-box.local</b>).</li>
    <li>Click <b>Pair with an Odoo instance</b>.</li>
    <li>Enter the Odoo server URL shown below.</li>
    <li>Enter the pairing code shown below when prompted.</li>
    <li>Once the box reports back, click <b>I've Paired</b>.</li>
</ol>
"""

_INSTRUCTIONS_BOX_HTML = """
<ol>
    <li>Plug the IoT Box into power, ethernet and an HDMI screen.</li>
    <li>Wait until the box boots — a pairing token appears on the screen.</li>
    <li>Type that exact token into the <b>Box Token</b> field below.</li>
    <li>Optionally fill the identifier (MAC / serial) and LAN IP.</li>
    <li>Click <b>Connect Box</b> — the box will be registered immediately.</li>
</ol>
"""


class IotPairingWizard(models.TransientModel):
    """Dual-mode IoT pairing wizard.

    * ``server`` mode — Odoo generates a one-time code; the user enters it
      on the IoT Box's local homepage. This is the existing flow.
    * ``box`` mode — the IoT Box displays a token on its HDMI screen at boot;
      the user copies that token into Odoo. The box is linked immediately.
    """
    _name = 'iot.pairing.wizard'
    _description = 'IoT Pairing Wizard'

    pairing_mode = fields.Selection([
        ('server', 'Use code generated by Odoo'),
        ('box', 'Use token displayed by the IoT Box'),
    ], string='Pairing Mode', default='server', required=True)

    iot_box_id = fields.Many2one(
        'iot.box', string='IoT Box', ondelete='cascade',
        help='Existing box record. Required for server-code mode; '
             'created automatically in box-token mode if left empty.',
    )
    box_name = fields.Char(
        string='Box Name',
        help='Friendly name to assign when creating a new box in box-token mode.',
    )
    box_token = fields.Char(
        string='Box Token',
        help='Copy here the token that appears on the IoT Box HDMI screen.',
    )

    pairing_code = fields.Char(string='Pairing Code', readonly=True)
    instructions = fields.Html(
        string='Instructions', readonly=True,
        compute='_compute_instructions',
    )
    server_url = fields.Char(
        string='Odoo Server URL', readonly=True,
        compute='_compute_server_url',
    )
    identifier = fields.Char(
        string='Box Identifier',
        help='If you already know the box identifier (MAC / serial), enter it now.',
    )
    ip_address = fields.Char(string='Box LAN IP')

    # ── Computed ─────────────────────────────────────────────────────────
    @api.depends('pairing_mode')
    def _compute_instructions(self):
        for rec in self:
            rec.instructions = (
                _INSTRUCTIONS_BOX_HTML if rec.pairing_mode == 'box'
                else _INSTRUCTIONS_SERVER_HTML
            )

    def _compute_server_url(self):
        base = self.env['ir.config_parameter'].sudo().get_param(
            'web.base.url', 'http://localhost:8069')
        for rec in self:
            rec.server_url = base

    # ── Actions ──────────────────────────────────────────────────────────
    def action_confirm_paired(self):
        """Unified entry point; dispatches to the chosen pairing mode."""
        self.ensure_one()
        if self.pairing_mode == 'box':
            return self._action_pair_with_box_token()
        return self._action_pair_with_server_code()

    def _action_pair_with_server_code(self):
        """Server-code flow: an existing box is in 'pairing' state and the
        user has entered the code on the box's homepage."""
        if not self.iot_box_id:
            raise UserError(_('No IoT Box selected.'))
        box = self.iot_box_id
        vals = {}
        if self.identifier:
            vals['identifier'] = self.identifier
        if self.ip_address:
            vals['ip_address'] = self.ip_address
        if vals:
            box.write(vals)

        if box.state == 'pairing':
            box.action_mark_connected()
        else:
            raise UserError(_(
                "This box is not in pairing mode. Generate a new code first."))

        self.env['iot.connection.log'].create({
            'iot_box_id': box.id,
            'event': 'paired',
            'message': _('Box paired via server code by %s') % self.env.user.name,
        })
        return self._open_box_form(box)

    def _action_pair_with_box_token(self):
        """Box-token flow: the user typed the token shown on the device's
        screen. Create or update the matching box record and mark it
        connected immediately."""
        if not self.box_token:
            raise UserError(_(
                'Please enter the token displayed on the IoT Box screen.'))
        token = self.box_token.strip()

        Box = self.env['iot.box']
        # Reuse an existing record if the token was already registered
        box = self.iot_box_id or Box.search(
            [('box_pairing_token', '=', token)], limit=1)

        vals = {
            'box_pairing_token': token,
            'state': 'connected',
            'last_heartbeat': fields.Datetime.now(),
            'pairing_expiry': False,
            'pairing_code': False,
        }
        if self.identifier:
            vals['identifier'] = self.identifier
        if self.ip_address:
            vals['ip_address'] = self.ip_address

        if box:
            box.sudo().write(vals)
        else:
            vals['name'] = self.box_name or _('IoT Box')
            # Use a sudo() create so non-system users can register boxes too
            box = Box.sudo().create(vals)

        box.message_post(
            body=_('Box connected via device-displayed token by %s.')
            % self.env.user.name)
        self.env['iot.connection.log'].sudo().create({
            'iot_box_id': box.id,
            'event': 'paired',
            'message': _('Box paired via box token by %s') % self.env.user.name,
        })
        return self._open_box_form(box)

    # ── Helpers ──────────────────────────────────────────────────────────
    def _open_box_form(self, box):
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'iot.box',
            'res_id': box.id,
            'view_mode': 'form',
            'target': 'current',
        }

    # ── Entry-point factories ────────────────────────────────────────────
    @api.model
    def action_open_box_mode(self):
        """Opens a blank wizard pre-set to box-token mode. Used by the
        'Connect IoT Box' menu entry."""
        return {
            'type': 'ir.actions.act_window',
            'name': _('Connect IoT Box'),
            'res_model': 'iot.pairing.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {'default_pairing_mode': 'box'},
        }
